I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/point_and_click/point_and_click.rpy", line 65, in script call
    call mito_mujer_bienestar
  File "game/point_and_click/point_and_click.rpy", line 65, in script call
    call mito_mujer_bienestar
renpy.script.LabelNotFound: could not find label 'mito_mujer_bienestar'.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/point_and_click/point_and_click.rpy", line 65, in script call
    call mito_mujer_bienestar
  File "renpy/ast.py", line 1622, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/point_and_click/point_and_click.rpy", line 65, in script call
    call mito_mujer_bienestar
  File "renpy/script.py", line 1161, in lookup
    raise LabelNotFound(original)
renpy.script.LabelNotFound: could not find label 'mito_mujer_bienestar'.

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
Latencia

Me quiere o no me quiere, pero ¿cómo quiero? 1.0.0-alpha
Sat Sep  6 19:08:07 2025
